config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :file_uploads, only: [:new, :create, :index, :destroy]

  # Custom route for shared files
  get '/files/:tiny_url', to: 'file_uploads#show', as: 'shared_file'

  # Set the root route to the sign-in page
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  belongs_to :user
  has_attached_file :file
  validates_attachment_content_type :file, content_type: ['image/jpeg', 'image/png', 'application/pdf', 'application/zip', 'text/plain', 'application/zip']
  validates_attachment_size :file, less_than: 1.gigabyte

  before_create :generate_tiny_url

  private

  def generate_tiny_url
    self.tiny_url = SecureRandom.urlsafe_base64(6)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :file_uploads, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Redirect to new upload page after successful sign-up
  # def after_sign_up_path_for(resource)
  #   new_file_upload_path  # Redirect to the new upload page
  # end

  def after_sign_in_path_for(resource)
    Rails.logger.debug "Redirecting to new file upload page"
     new_file_upload_path  # Redirect to the new upload page
  end
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  before_action :authenticate_user!

  def new
    @file_upload = current_user.file_uploads.build
  end

  def create
    @file_upload = current_user.file_uploads.build(file_upload_params)
    if @file_upload.save
      redirect_to file_uploads_path, notice: 'File uploaded successfully.'
    else
      render :new
    end
  end

  def index
    @file_uploads = current_user.file_uploads
  end

  def destroy
    @file_upload = current_user.file_uploads.find(params[:id])
    @file_upload.destroy
    redirect_to file_uploads_path, notice: 'File deleted successfully.'
  end

  def show
    @file_upload = FileUpload.find_by(tiny_url: params[:tiny_url])
    send_file @file_upload.file.path, type: @file_upload.file.content_type, disposition: 'inline'
  end
  

  private

  def file_upload_params
    params.require(:file_upload).permit(:title, :description, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/file_uploads/create.html.erb
<h1>Files#create</h1>
<p>Find me in app/views/files/create.html.erb</p>

app/views/file_uploads/destroy.html.erb
<h1>Files#destroy</h1>
<p>Find me in app/views/files/destroy.html.erb</p>

app/views/file_uploads/index.html.erb
<h2>Your Files <button> <a href="/file_uploads/new" >Create a New Upload</a></button></span></h2> 
<% @file_uploads.each_with_index do |file, index| %>
  <div>
     <h3><%=index+1%>. &nbsp;&nbsp;<%= file.title %></h3>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;<%= file.description %></p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;<strong>File Type:</strong> <%= file.file.content_type %></p>
    <% if file.file.content_type.start_with?('image') %>
      <div>
        <img src="<%= file.file.url %>" alt="<%= file.title %>" style="max-width: 200px; max-height: 200px;" />
      </div>
    <% end %>

    <% unless file.file.content_type.start_with?('image') %>
      <div>
        <%= link_to 'Download', file.file.url, target: '_blank' %>
      </div>
    <% end %>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Delete', file_upload_path(file), method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <p>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Share', shared_file_path(file.tiny_url) %></p>
  </div>
<% end %>

app/views/file_uploads/new.html.erb
<button style="margin-bottom: 15px"> <a href="/file_uploads" >See All Uploads</a></button></span><br>
<%= form_for @file_upload, html: { multipart: true } do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
  
    <div>
      <%= f.label :file %>
      <%= f.file_field :file %>
    </div>
  
    <div>
      <%= f.submit "Upload" %>
    </div>
  <% end %>
  

app/views/file_uploads/show.html.erb
<h1>Files#show</h1>
<p>Find me in app/views/files/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUploadShareAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>